name: cpp-cmake-mingw-prebuilt-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*'

permissions:
    contents: write
    
jobs:
  build:
    strategy:
      matrix:
        compiler:
        - {
            name: "x86_64-8.1.0-release-posix-seh-rt_v6-rev0",
            url: "https://github.com/dirkarnez/cpp-tools/raw/main/x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z"
          }
        # - {
        #     name: "winlibs-x86_64-posix-seh-gcc-11.2.0-mingw-w64-9.0.0-r1",
        #     url: "https://github.com/brechtsanders/winlibs_mingw/releases/download/11.2.0-12.0.1-9.0.0-r1/winlibs-x86_64-posix-seh-gcc-11.2.0-mingw-w64-9.0.0-r1.zip"
        #   }
        # - {
        #     name: "msvc2019"
        #   }

 
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - shell: cmd
        run: |
          curl https://github.com/conan-io/conan/releases/download/2.0.14/conan-win-64.zip -L -O &&^
          7z x conan-win-64.zip -o"conan-win-64"
          
      - shell: cmd
        run: |
          cd conan-win-64 &&^
          conan search * -r=conancenter
          
# conan search "*" --table=file.html -q "arch=x86_64 AND build_type=Release AND os=Windows" -r=conancenter
